--- 
sequence: 
  lights: 
  - - our
    - light
    - "on"
  - - our
    - lights
    - "on"
room: 
- name: our
  device: 
  - light
  - lights
  - kettle
  - tv
- name: dining
  device:
  - light
  - lights
- name: harry
  device:
  - light
- name: tommy
  device:
  - light
- name: lounge
  device:
  - light
  - lights
- name: kitchen
  device:
  - kettle
  - toaster
  - radio
  - socket
- name: cloakroom
  device:
  - light
- name: hall
  device:
  - light
- name: landing
  device:
  - light
calendar: 'https://www.google.com/calendar/feeds/sgvkej0k4gdv59eu3adi6gddr8%40group.calendar.google.com/private-649b00dd25c2f90b7cfceb519b8ac2b5/basic'
sequence:
  bed:
  - - our
    - light
    - 'off'
  - - our
    - lights
    - 'off'
