---
host: 192.168.1.64
calendar: 'https://www.google.com/calendar/feeds/sgvkej0k4gdv59eu3adi6gddr8%40group.calendar.google.com/private-649b00dd25c2f90b7cfceb519b8ac2b5/basic'
room:
  our:
  - light
  - lights
  - kettle
  - tv
  dining:
  - light
  - lights
  harry:
  - light
  tommy:
  - light
  lounge:
  - light
  - lights
  kitchen:
  - kettle
  - toaster
  cloakroom:
  - light
  hall:
  - light
  landing:
  - light
sequence:
  bed:
  - - our
    - light
    - 'off'
  - - our
    - lights
    - 'off'
